Repository Alohomora-team/2019.2-AlohomoraBot, pull requests merged in 2019-11, with the labels that each got.

#32 3.1 atualizar interacao cadastro
  CHANGELOG.md
  bot/main.py
  bot/register.py
  bot/settings.py
  bot/validator.py
  docker/bot/requirements.txt
Labels: enhancement

#37 Correção do bug na criação do morador
  bot/register.py
Labels: bug

#43 42 deploy bot
  .travis.yml
  bot/main.py
  bot/settings.py
  deploy.Dockerfile
  docker-compose.yml
  heroku.yml
Labels: DevOps

#50 49 hotfix db bot
  .gitignore
  bot/database.db
Labels: bug

#52 #51 adiciona variavel de ambiente 'API_TOKEN'
  bot/settings.py
Labels: DevOps

#54 48 adicionar robustez cadastro voz
  bot/resident/register_resident.py
  bot/resident/resident_auth.py
  bot/validator.py
  docker/bot/requirements.txt
Labels: enhancement
